[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add= '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'js'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add='''
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
'''
