[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# color scheme

[[plugins]]
repo='zenorocha/dracula-theme'

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  set background=dark
'''
[[plugins]]
repo = 'kakkyz81/evervim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add= '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'
