[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add= '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
