
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
tap neovim/neovim

brew git
brew neovim
brew peco
brew zsh
brew tmux
brew the_silver_searcher
brew reattach-to-user-namespace
brew python3
brew ghq
brew coreutils
brew tig
brew fzf
brew rename
brew jq

cask iterm2
cask karabiner
cask alfred
cask evernote
cask clipy
cask shiftit
cask caffeine
cask intel-power-gadget

# qucik look
cask betterzipql
cask qlmarkdown
cask qlstephen
cask quciklook-json
