[custom.arch]
command = "uname -m"
when = "true"
os = "macos"
# format = " ($output)"


# [time]
# disabled = false
# format = '🕙[\[ $time \]]($style) '
# time_format = "%T"
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
