
# ignore /etc/zprofile, /etc/zshrc, /etc/zlogin, and /etc/zlogout
# ref. http://zsh.sourceforge.net/Doc/Release/Files.html
# ref. http://zsh.sourceforge.net/Doc/Release/Options.html#index-GLOBALRCS
# But this does not work for interactive shell (on mac?)
setopt no_global_rcs

## 重複パスを登録しない
typeset -U path PATH cdpath fpath manpath

# setting for zprof restart zsh
zmodload zsh/zprof

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.cache

# zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export HISTFILE=$XDG_DATA_HOME/zsh/history

# sqlite
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history

# vim
# export VIMINIT=":source $XDG_CONFIG_HOME"/vim/vimrc

# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
source "/Users/vinter/.rover/env"
