export DOTFILES="$HOME/.dotfiles"
# export ZSHHOME="$ZDOTDIR/zsh.d"

. $DOTFILES/etc/libs.zsh
. "$ZDOTDIR/zsh.d.sync/env_path.zsh"

evalcache "sheldon" "sheldon source"

# Move under plugins
# evalcache "rtx" "rtx activate zsh"
evalcache "mise" "~/.local/bin/mise activate zsh"

if has zoxide; then
  evalcache "zoxide" "zoxide init zsh"
fi

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

# #setting for zprof
# if type zprof > /dev/null 2>&1;then
#   zprof | less
# fi
# source "$HOME/.rye/env"

