export DOTFILES="$HOME/.dotfiles"
# export ZSHHOME="$ZDOTDIR/zsh.d"

. $DOTFILES/etc/libs.zsh
. "$ZDOTDIR/zsh.d.sync/env_path.zsh"

evalcache "sheldon" "sheldon source"

# Move under plugins
# evalcache "rtx" "rtx activate zsh"
evalcache "mise" "~/.local/bin/mise activate zsh"

if has zoxide; then
  evalcache "zoxide" "zoxide init zsh"
fi

# #setting for zprof
# if type zprof > /dev/null 2>&1;then
#   zprof | less
# fi
# source "$HOME/.rye/env"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/vinter/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/vinter/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/vinter/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/vinter/google-cloud-sdk/completion.zsh.inc'; fi
