export DOTFILES="$HOME/.dotfiles"
# export ZSHHOME="$ZDOTDIR/zsh.d"

. $DOTFILES/etc/libs.zsh
. "$ZDOTDIR/zsh.d.sync/env_path.zsh"

evalcache "sheldon" "sheldon source"

# #setting for zprof
# if type zprof > /dev/null 2>&1;then
#   zprof | less
# fi
