[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
" Plugin key-mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" imap <expr><TAB>
"  \ pumvisible() ? "\<C-n>" :
"  \ neosnippet#expandable_or_jumpable() ?
"  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
'''


# color scheme
[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kakkyz81/evervim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Shougo/unite-build'
depends = 'unite.vim'

##################################################################
# syntax

[[plugins]] # js syntax
repo = 'othree/yajs.vim'
# repo = 'jelera/vim-javascript-syntax'
on_ft = ['js', 'ts']

[[plugins]] # js syntax
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['js', 'ts']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

