[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# color scheme

# [[plugins]] # solarized
# repo = 'altercation/vim-colors-solarized'
# hook_add = '''
#   set background=dark
# '''
[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'

# other
# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kakkyz81/evervim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add='''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
" insert modeで開始
" let g:unite_enable_start_insert = 1

" 大文字小文字を区別しない
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1

" unite grep に ag(The Silver Searcher) を使う
if executable('ag')
  let g:unite_source_rec_async_command='ag --nocolor --nogroup --hidden -g ""'
endif

'''

[[plugins]]
repo = 'Shougo/unite-build'
depends = 'unite.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
let g:syntastic_javascript_checkers=['eslint']

" エラー行に sign を表示
let g:syntastic_enable_signs = 1
" location list を常に更新
let g:syntastic_always_populate_loc_list = 0
" location list を常に表示
let g:syntastic_auto_loc_list = 0
" ファイルを開いた時にチェックを実行する
let g:syntastic_check_on_open = 1
" :wq で終了する時もチェックする
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add= '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add = '''
let g:formatdef_jsbeautify_javascript = '"js-beautify --config ~/.jsbeautifyrc"'
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
let g:vimfiler_as_default_explorer = 1
'''
