[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'rb'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'


[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add='''
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_path = '.*'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'scrooloose/syntastic'
on_event = ['FocusLost', 'CursorHold', 'BufWritePre']
hook_add = '''
let g:syntastic_javascript_checkers=['eslint']

" エラー行に sign を表示
let g:syntastic_enable_signs = 1
" location list を常に更新
let g:syntastic_always_populate_loc_list = 0
" location list を常に表示
let g:syntastic_auto_loc_list = 0
" ファイルを開いた時にチェックを実行する
" "let g:syntastic_check_on_open = 1
" :wq で終了する時もチェックする
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add = '''
let g:formatdef_jsbeautify_javascript = '"js-beautify --config ~/.jsbeautifyrc"'
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
" insert modeで開始
" let g:unite_enable_start_insert = 1

" 大文字小文字を区別しない
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1

" unite grep に ag(The Silver Searcher) を使う
if executable('ag')
  let g:unite_source_rec_async_command='ag --nocolor --nogroup --hidden -g ""'
endif
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_if = "isdirectory(bufname('%'))"
hook_add = '''
let g:vimfiler_as_default_explorer = 1
'''

[[plugins]]
repo = 'tyru/caw.vim'
on_path = '.*'
hook_add='''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''
