[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# color scheme

# [[plugins]] # solarized
# repo = 'altercation/vim-colors-solarized'
# hook_add = '''
#   set background=dark
# '''
[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'

# other
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kakkyz81/evervim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'


[[plugins]]
repo = 'tyru/caw.vim'
hook_add='''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''
