##################################################################
# deoplete

# [[plugins]]
# repo = 'carlitux/deoplete-ternjs'
# lazy = 0
# depends = 'tern_for_vim'

# [[plugins]]
# # Required: run 'npm install' in the plugin dir.
# repo = 'ternjs/tern_for_vim'
# lazy = 0
# hook_add = '''
# let tern#is_show_argument_hints_enabled = 1
# '''

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'xaizek/vim-inccomplete'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 0
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''
