[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'rb'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'


[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add='''
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_path = '.*'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

# [[plugins]]
# repo = 'scrooloose/syntastic'
# on_event = ['FocusLost', 'CursorHold', 'BufWritePre']
# hook_source = '''
# source ~/.config/nvim/plugins/syntastic.rc.vim
# '''

[[plugins]]
repo = 'Chiel92/vim-autoformat'
hook_add = '''
let g:formatdef_jsbeautify_javascript = '"js-beautify --config ~/.jsbeautifyrc"'
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
source ~/.config/nvim/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_if = "isdirectory(bufname('%'))"
hook_add = '''
let g:vimfiler_as_default_explorer = 1
'''

[[plugins]]
repo = 'tyru/caw.vim'
on_path = '.*'
hook_add='''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_path = '.*'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'js'

[[plugins]]
repo = 'neomake/neomake'
on_path = '.*'
hook_add = '''
source  ~/.config/nvim/plugins/neomake.rc.vim
'''

