##################################################################
# deoplete

# [[plugins]]
# repo = 'carlitux/deoplete-ternjs'
# on_ft = 'js'
# hook_add = '''
#   let g:tern_request_timeout = 1
#   let g:tern_show_signature_in_pum = 0
#   " Use tern_for_vim.
#   let g:tern#command = ["tern"]
#   let g:tern#arguments = ["--persistent"]
# '''

[[plugins]]
# Required: npm install tern
# run 'npm install' in the plugin dir.
repo = 'ternjs/tern_for_vim'
on_ft = 'js'
lazy = 0

# doesn't work
# [[plugins]]
# Required:
# libclang
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
lazy = 0
hook_source= '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''
