##################################################################
# nvim plugins

# [[plugins]]
# repo = 'carlitux/deoplete-ternjs'
# on_ft = ['javascript', 'javascript.jsx']
# on_i = 1
# hook_source = '''
# let g:tern_request_timeout = 1
# let g:tern#command = ['tern']
# let g:tern#arguments = ['--persistent']
# '''

[[plugins]]
repo = 'w0rp/ale'
on_event = 'BufEnter'
hook_source = '''
source  ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
# on_i = 1
on_event = 'BufEnter'
hook_add = '''
let g:deoplete#auto_complete_delay=50
'''
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# [[plugins]]
# # usefull but too slow
# repo = 'ternjs/tern_for_vim'
# lazy = 0
# on_ft = 'javascript'
# hook_add = '''
#   let tern#is_show_argument_hints_enabled = 1
# '''
# build = 'npm install'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'

# [[plugins]]
# repo = 'tweekmonster/deoplete-clang2'
# on_ft = ['c', 'cpp', 'cc']
# hook_add = '''
# if has('mac')
#   let g:deoplete#sources#clang#flags = ['-darwin=10.11']
# endif
# '''

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['sh', 'zsh']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
if = "has('nvim')"
depends = 'deoplete'
on_event = 'BufEnter'
# on_i = 1
hook_add = '''
source  ~/.config/nvim/plugins/lang-client.rc.vim
'''
build = 'bash install.sh'
rev = 'next'
