##################################################################
# deoplete

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
lazy = 0
hook_add = '''
  let g:tern_request_timeout = 1
  " let g:tern_show_signature_in_pum = 0
'''

[[plugins]]
# Required: run 'npm install' in the plugin dir.
repo = 'ternjs/tern_for_vim'
lazy = 0

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'xaizek/vim-inccomplete'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 0
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''
