# [[plugins]]
# # ruby complement
# repo = 'osyo-manga/vim-monster'
# on_ft = 'rb'

# [[plugins]]
# repo = 'Shougo/neosnippet'
# depends = 'neosnippet-snippets'
# on_event = 'InsertCharPre'
# on_ft = 'snippet'

[[plugins]]
# Auto close parentheses and repeat by dot dot dot...
repo = 'cohama/lexima.vim'
on_path = '.*'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'
hook_add = '''
if has('mac')
  let g:EditorConfig_core_mode = 'external_command'
else
  let g:EditorConfig_core_mode = 'python_external'
endif
'''

# [[plugins]]
# repo = 'Shougo/unite.vim'
# depends = 'neomru.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/unite.rc.vim
# '''

[[plugins]]
# to use unite file_mru
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
# comment out easyly
repo = 'tyru/caw.vim'
on_path = '.*'
hook_add='''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_path = '.*'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_path = '.*'
hook_add = '''
let g:quickrun_config = {
\   "_" : {
\       "runner" : "vimproc",
\       "runner/vimproc/updatetime" : 40,
\   }
\}
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_path = '.*'
hook_add = '''
let g:indentLine_enabled = 1
let g:indentLine_fileTypeExclude = ['help', 'json']
let g:indentLine_conceallevel=1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'

# [[plugins]]
# repo = 'Quramy/tsuquyomi'
# on_ft = 'typescript'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
'''
